#STUDENT_NAME: ANMOLDEEP SANDHU
#STUDENT_ID: 10440057
#AGE GUESSING SYSYTEM

#!/bin/bash

Age_Guessed=$(($RANDOM % 100 )) # A VARIABLE DECLARED TO STORE THE RANDOM AGE GENERATED BY THE FUNCTION.

for (( ; ; ))                   #FOR STATEMENT TO REPEAT THE LOOP.
 do
  read -p  "Guess the age " Age_of_User     # TO PRINT MESSAGE FOR USER 
  if [ $Age_of_User -eq $Age_Guessed ]      # -EG FUNCTION USED TO COMPARE THE AGE 
   then
   echo "your guess is correct"
   break                                    # A STATEMENT WHICH STOP THE PROGRAM IF A STATEMENT IS TRUE.
    else 
     echo "your age guess is wrong"
   if [ $Age_of_User -ge $Age_Guessed ] # ANOTHER FUNCTION TO DO COMPARISON
    then                                 # IF ABOVE STATEMENT TRUE THE FOLLOWING MESSAGE WILL PRINT.
      echo "your guess is high"
     else                                 # IF ABOVE STATEMENT IS FALSE THE FOLLOWING MESSAGE WILL PRINT.
      echo "your guess is low"
     fi                                   
  fi                                        
done                              
